apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.brownrecorder'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()

android {
  namespace "expo.modules.brownrecorder"
  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}
